config/routes.rb
Rails.application.routes.draw do

root "bets#index"

devise_for :users, :controllers => { registrations: 'registrations' }

resources :bets do
	
	member do
		put "like" => "bets#upvote"
		put "unlike" => "bets#downvote"
	end

end

  
end

app/models/bet.rb
class Bet < ActiveRecord::Base

	acts_as_votable

	belongs_to :user
	
	has_attached_file :image, :styles => { :medium => "300x400>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	validates :name, :betamount, :potentialwins, presence: true
  	validates :betamount, :potentialwins, numericality: true


end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_voter

  has_many :bets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController

	before_action :find_bet, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]
	before_action :owns_bet, only: [:edit, :update, :destroy]

	def index
		@bets = Bet.all.order(:cached_votes_score => "DESC").limit(9)
	end

	def show

	end

	def new
		@bet = current_user.bets.new
	end

	def create
		@bet = current_user.bets.create(bet_params)
		if @bet.save
			flash[:success] = "Bet Added, Good Luck!"
			redirect_to @bet
		else
			render "new"
		end
	end

	def edit
	end

	def update
		if @bet.update(bet_params)
			flash[:success] = "Bet Updated, Good Luck!"
			redirect_to @bet
		else
			render "edit"
		end
	end

	def destroy
		@bet.delete
		flash[:danger] = "Bet Deleted, Why not submit another?"
		redirect_to root_path

	end



	def upvote
		@bet.upvote_from current_user
		redirect_to @bet
	end

	def downvote
		@bet.downvote_from current_user
		redirect_to @bet
	end



	private

	def bet_params
		params.require(:bet).permit(:name, :betamount, :potentialwins, :image, :bet_id)
	end

	def find_bet
		@bet = Bet.find(params[:id])
	end

	def owns_bet
		unless @bet.user_id == current_user.id
			flash[:danger] = "Naughty, That isnt your bet!"
			redirect_to root_path
		end

	end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%=	 simple_form_for @bet, html: {multipart: true} do |f|  %>

		<% if @bet.errors.any? %>

			<div class="errors">
				
				<%= pluralize(@bet.errors.count, "Error") %> Prevented this form from submitting.
				
				<ul>
					<% @bet.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>

			</div><!-- /.errors -->
			
		<% end %>



		<%= f.input :name, input_html: { class: "form-control" }, label: "Name of Bet", placeholder: "First Goalscorer or I'm feeling lucky!" %>
		<%= f.input :image, input_html: { class: "form-control" }, label: "Upload bet slip image" %>
		<%= f.input :betamount, input_html: { class: "form-control" }, label: "Bet Stake", placeholder: "£10" %>
		<%= f.input :potentialwins, input_html: { class: "form-control" }, label: "Expected Returns", placeholder: "£100" %>

		<%= f.button :submit, class: "btn btn-default" %> 
<% end %>

app/views/bets/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="form-bg">
	<h2>Edit your bet</h2>

	<%= render "form" %>

	</div><!-- /.form-bg -->
	
</div><!-- /.col-md-6 col-md-offset-3 -->

app/views/bets/index.html.erb
<div class="jumbotron">

	<div class="text-center">

		<% if !user_signed_in? %>
	
		<h1>Welcome to SocialBet</h1>
		<p>Social Networking for gamblers</p>

		<a href="" class="btn btn-primary">Sign Up</a>

		<% else %>

		<h1>Welcome Back</h1>

		<p>Take a look at the top rated bets below, or submit your own</p>

		<%= link_to "Submit a Bet", new_bet_path, class: "btn btn-primary"  %>

		<% end %>

	</div><!-- /.text-center -->


</div><!-- /.jumbotron -->

<div class="row">

	<div class="text-center">
	
	<div class="col-md-4">
		<h2>Heading 1</h2>
	
		<p>Some text here Some text here Some text here Some text here Some text here</p>

		<a href="" class="btn btn-default">Top Voted Bets</a>

	</div><!-- /.col-md-4 -->

	<div class="col-md-4">
		<h2>Heading 1</h2>
	
		<p>Some text here Some text here Some text here Some text here Some text here</p>

		<a href="" class="btn btn-default">This Weeks winners</a>

	</div><!-- /.col-md-4 -->

	<div class="col-md-4">
		<h2>Heading 1</h2>
	
		<p>Some text here Some text here Some text here Some text here Some text here</p>
		
		<a href="" class="btn btn-default">Top Deals</a>
	</div><!-- /.col-md-4 -->

	</div><!-- /.text-center -->

</div><!-- /.row -->


<div class="row">
	<div class="col-md-12">
		
		<h3>Top Voted Bets</h3>

		<hr />

		<% @bets.each do |bet| %>

			<div class="col-md-4 col-sm-6">

				<div class="bet-container">
		
					<h4 class="betname"><%= link_to bet.name, bet %></h4>

					<p class="bet-amount">Amount Staked: <%= number_to_currency(bet.betamount, unit: "£") %></p><!-- /.bet-amount -->

					<p class="potential">Potential Winnings: <%= number_to_currency(bet.potentialwins, unit: "£") %></p><!-- /.potential -->

					<div class="votes pull-right">

						<span class="glyphicon glyphicon-thumbs-up"></span>

						<span class="badge liked"><%= bet.get_upvotes.size %></span>

						<span class="glyphicon glyphicon-thumbs-down"></span>

						<span class="badge unliked"><%= bet.get_downvotes.size %></span>

					</div><!-- /.votes -->

				</div><!--/bet container-->
			
			</div><!--/col md 4-->

		<% end %>


	</div><!-- /.col-md-12 -->


</div><!-- /.row -->


<div class="row">
	<div class="col-md-12">
		<h3>Bets from people you follow</h3>
		<hr />

		
	</div><!-- /.col-md-12 -->
</div><!-- /.row -->

app/views/bets/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="form-bg">
	<h2>Upload your bet</h2>

	<%= render "form" %>

	</div><!-- /.form-bg -->
	
</div><!-- /.col-md-6 col-md-offset-3 -->

app/views/bets/show.html.erb
<div class="col-md-6">
	
	<div class="panel panel-default">
		<div class="panel-heading"><h2>Bet Slip</h2></div><!-- /.panel-heading -->

		<div class="panel-body">
			<%= image_tag @bet.image.url,  class: "img-responsive" %>
		</div><!-- /.panel-body -->

	</div><!-- /.panel panel-default -->

</div><!-- /.col-md-6 -->



<div class="col-md-6">
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2>Bet Details</h2>
		</div><!-- /.panel-heading -->

		<div class="panel-body">
			<%= @bet.name %>
			<p class="bet-amount">Bet Amount Placed:<%= number_to_currency(@bet.betamount, unit: "£") %></p><!-- /.bet-amount -->
			<p class="potential-wins">Potential Wins:<%= number_to_currency(@bet.potentialwins, unit: "£") %></p><!-- /.potential-wins -->
		</div><!-- /.panel-body -->

		<div class="panel-footer">
			
			<%= link_to "Place Similar Bet", "", class: "btn btn-primary"  %>

			<div class="pull-right">
				<% if !user_signed_in? %>
					
				<% else %>
					
					<%= link_to like_bet_path(@bet), class: "like", method: :put do  %>
						
						<button class="btn btn-default">
							<span class="glyphicon glyphicon-thumbs-up"></span>

							<span class="badge liked"><%= @bet.get_upvotes.size %></span>
						</button>
					<% end %>

					<%= link_to unlike_bet_path(@bet), class: "like", method: :put do  %>
						
						<button class="btn btn-default">
							<span class="glyphicon glyphicon-thumbs-down"></span>

							<span class="badge unliked"><%= @bet.get_downvotes.size %></span>
						</button>
					<% end %>

				<% end %>
			</div><!-- /.pull-right -->

			<div class="clear"></div>
		</div><!-- /.panel-footer -->

	</div><!-- /.panel -->

	<div class="panel panel-default">
		
		<div class="panel-heading"><h2><%= @bet.user.name %> stats</h2></div><!-- /.panel-heading -->

			<div class="panel-body">

				


			</div><!-- /.panel-body -->



		<div class="panel-footer">
			
			<div class="pull-right">

				<% if user_signed_in? && current_user.id == @bet.user_id %>
					<%= link_to "Edit Bet", edit_bet_path, class: "btn btn-warning"  %>
					<%= link_to "Delete Bet", @bet, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
				<% end %>
			</div><!-- /.pull-right -->

			<div class="clear"></div>

		</div><!-- /.panel-footer -->

	</div><!-- /.panel panel-default -->

</div><!-- /.col-md-8 -->

 

app/views/layouts/_nav.html.erb
	<nav class="navbar navbar-default">
		
		<div class="container">
			
			<%= link_to "SocialBet", root_path, class: "navbar-brand" %>

			<div class="pull-right">

				<% if user_signed_in? %>
				
					<%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "btn btn-default navbar-btn" %>

					<%= link_to "Add Bet", new_bet_path, class: "btn btn-primary navbar-btn"  %>

				<% else %>

					<%= link_to "Sign In", new_user_session_path, class: "btn btn-default navbar-btn" %>

					<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary navbar-btn"  %>

				<% end %>

			</div><!-- /.pull-right -->

		</div><!-- /.container -->

	</nav><!-- /.navbar navbar-default -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialbet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render "layouts/nav" %>

	<div class="container">

		<% flash.each do |key, value | %>
	
			<div class="alert alert-<%= key %>"><%= value %></div><!-- /.alert -->

	    <% end %>

	<%= yield %>

	</div><!-- /.container -->

</body>
</html>